# Generated by Django 5.0 on 2023-12-09 08:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_item_barcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='barcode',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
