# Generated by Django 5.0 on 2023-12-09 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='court_date',
            field=models.DateField(default="2023-12-12"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(default="Default text for description"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='digital_media',
            field=models.CharField(default="media", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='disposition',
            field=models.CharField(default="disposition", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='location',
            field=models.CharField(default="location", max_length=255),
            preserve_default=False,
        ),
    ]
